baseurl = "http://delputnam.me/"
languageCode = "en-us"
title = "Del Putnam"
theme = "hugo-theme-delputnam"
paginate = 25
paginatePath = "page"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
MetaDataFormat = "yaml"
CanonifyUrls = "true"

[author]
    name = "Del Putnam"
    email = "del@putnams.net"
    twitter = "delputnam"
    facebook = "delputnam"

[social]
	facebook = "delputnam"
	facebook_admin = "delputnam"
	twitter = "delputnam"

[params]
	description = "Answering all your questions, one day at a time."
	author = "Del Putnam"
	google_analytics_id = "UA-45369150-4"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home'></i>"
    weight = 1
    identifier = "home"
    url = "/"

#[[menu.main]]
#	name = "Photos"
#	pre = "<i class=\"fa fa-camera\"></i>"
#	weight = 50
#	identifier = "photos"
#	url = "/photo/"
